name: CI - b3pulse

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'v2.3.1'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Build app
        run: |
          go mod tidy
          go build -o b3pulse ./cmd/main.go

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Run tests and generate coverage
        run: |
          go mod tidy
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
          echo "coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')" >> $GITHUB_ENV

      - name: SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: guttosm_b3pulse
          SONAR_ORGANIZATION: guttosm-personal-projects

  migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: userdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run goose migrations
        env:
          GOOSE_DRIVER: postgres
          GOOSE_DBSTRING: postgres://postgres:postgres@localhost:5432/userdb?sslmode=disable
        run: |
          $HOME/go/bin/goose -dir db/migrations up
